module.exports = {
  ECMAScript: {
    Object: [
      'Object/hasOwnProperty',
      'Object/getPrototypeOf',
      'Object/isPrototypeOf',
      'Object/propertyIsEnumerable',
      'Object/assign',
      'Object/create',
      'Object/is',
      'Object/defineProperty',
      'Object/defineProperties',
      'Object/keys',
      'Object/values',
      'Object/entries',
      'Object/fromEntries',
      'Object/getOwnPropertyDescriptor',
      'Object/getOwnPropertyDescriptors',
      'Object/getOwnPropertyNames',
      'Object/getOwnPropertySymbols',
      'Object/preventExtensions',
      'Object/seal',
      'Object/freeze',
      'Object/isExtensible',
      'Object/isSealed',
      'Object/isFrozen',
      'Object/setPrototypeOf',
    ],
    String: [
      'String/charAt',
      'String/charCodeAt',
      'String/codePointAt',
      'String/concat',
      'String/endsWith',
      'String/includes',
      'String/indexOf',
      'String/lastIndexOf',
      'String/localeCompare',
      'String/match',
      'String/normalize',
      'String/padEnd',
      'String/padStart',
      'String/repeat',
      'String/replace',
      'String/search',
      'String/slice',
      'String/split',
      'String/startsWith',
      'String/fromCharCode',
      'String/fromCodePoint',
      'String/substr',
      'String/substring',
      'String/to...Case',
      'String/trim',
    ],
    Array: [
      'Array/from',
      'Array/of',
      'Array/isArray',
      'Array/concat',
      'Array/copyWithin',
      'Array/entries',
      'Array/flat',
    ],
    Math: [
      'Math/sin',
      'Math/tan',
      'Math/cos',
      'Math/abs',
      'Math/clz32',
      'Math/floor',
      'Math/formulas',
      'Math/fround',
      'Math/imul',
      'Math/max',
      'Math/random',
      'Math/sign',
      'Math/trunc',
    ],
    Function: ['Function/call', 'Function/apply', 'Function/bind'],
    Promise: ['Promise/promise', 'Promise/promiseA+', 'Promise/promiseWheel'],
    Proxy: ['Proxy/proxy'],
  },
}
